INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 
INSERT INTO users (name, lastname, email, identification, password,direction) VALUES ('pedro', 'castro',  'cc@gmail.com','99999999','33e32','algun lugar del mundo') 

